name: pkgdown

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  pkgdown:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install pkgdown
        run: |
          Rscript -e 'install.packages("pkgdown")'

      - name: Install package dependencies
        run: |
          Rscript -e 'install.packages("remotes")'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Build site
        run: |
          Rscript -e 'pkgdown::build_site()'

      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
